In [1]:
import numpy as np;
import pandas as pd;
import seaborn as sns;
import matplotlib.pyplot as plt;

In [2]:
data = pd.read_csv("CombinedData.csv");

In [3]:
data[:20] #just to see what the data looks like. DIV4 has no JF646 so therefore NaN.

,Replicate,DIV,Filename,ROI_orig,ROI_eroded,Circularity,Nup153,JFX554,JF646,JF646_unique,Genotype
0,1,4,0608_10_WT_DIV4_Image1-Nup153-1.tif,52.0425,40.9482,0.95181,5.4703,4.8110,NaN,NaN,0
1,1,4,0608_10_WT_DIV4_Image1-Nup153-2.tif,61.2855,49.4082,0.99609,6.5576,5.3432,NaN,NaN,0
2,1,4,0608_10_WT_DIV4_Image2-Nup153-1.tif,50.2389,39.2490,0.93975,6.7008,5.4269,NaN,NaN,0
3,1,4,0608_10_WT_DIV4_Image2-Nup153-2.tif,42.9336,33.0624,0.97223,5.5955,5.3233,NaN,NaN,0
4,1,4,0608_10_WT_DIV4_Image3-Nup153-1.tif,52.2486,40.8753,0.91679,6.8746,6.1162,NaN,NaN,0
5,1,4,0608_10_WT_DIV4_Image3-Nup153-2.tif,57.7665,46.1601,0.97484,7.7123,6.8457,NaN,NaN,0
6,1,4,0608_10_WT_DIV4_Image3-Nup153-3.tif,59.0850,47.0295,0.91088,4.9756,4.4440,NaN,NaN,0
7,1,4,0608_10_WT_DIV4_Image4-Nup153-1.tif,51.7356,40.4631,0.90686,6.3515,5.3382,NaN,NaN,0
8,1,4,0608_10_WT_DIV4_Image4-Nup153-2.tif,45.9882,35.6796,0.96070,6.0539,4.8207,NaN,NaN,0
9,1,4,0608_10_WT_DIV4_Image5-Nup153-1.tif,62.1738,49.9752,0.95062,7.5838,6.3231,NaN,NaN,0
10,1,4,0608_10_WT_DIV4_Image5-Nup153-2.tif,56.2824,44.8317,0.96353,5.3534,4.9072,NaN,NaN,0
11,1,4,0608_10_WT_DIV4_Image6-Nup153-1.tif,60.4089,47.6190,0.85100,6.7410,5.6700,NaN,NaN,0
12,1,4,0608_10_WT_DIV4_Image6-Nup153-2.tif,52.6239,41.6295,0.97620,6.0294,4.9965,NaN,NaN,0
13,1,4,0608_10_WT_DIV4_Image6-Nup153-3.tif,68.5557,55.7973,0.96342,6.0935,5.4304,NaN,NaN,0
14,1,4,0608_10_WT_DIV4_Image6-Nup153-4.tif,60.2766,48.4452,0.98725,6.2338,5.5733,NaN,NaN,0
15,1,4,0608_10_WT_DIV4_Image7-Nup153-1.tif,45.7830,35.3637,0.94131,6.1362,4.6941,NaN,NaN,0
16,1,4,0608_10_WT_DIV4_Image7-Nup153-2.tif,40.9725,30.9852,0.91709,4.5828,4.1310,NaN,NaN,0
17,1,4,0608_10_WT_DIV4_Image8-1-Nup153-1.tif,52.1298,41.0157,0.95596,6.8267,6.0708,NaN,NaN,0
18,1,4,0608_10_WT_DIV4_Image8-1-Nup153-2.tif,48.2922,37.8360,0.98392,6.3696,5.4446,NaN,NaN,0
19,1,4,0608_10_WT_DIV4_Image8-1-Nup153-3.tif,53.4636,42.2199,0.96270,5.4477,4.8792,NaN,NaN,0

In [4]:
df = data.iloc[:,[0,1,6,10]]; #Replicate, DIV, Nup153, JFX554, JF646, JF646_unique (length of JFX554 same as Nup153 )

# N per replicate per DIV
df.groupby(['DIV', 'Replicate','Genotype']).size()

# Note genotype = 0 is WT, 1 = KO

DIV  Replicate  Genotype
4    1          0           20
                1           17
     2          0           22
                1           18
     3          0           15
                1           20
6    1          0           18
                1           22
     2          0           17
                1           13
     3          0           19
                1           16
8    1          0           14
                1           18
     2          0           22
                1           11
     3          0           18
                1           22
10   1          0           17
                1           20
     2          0           19
                1            9
     3          0           17
                1           17
dtype: int64

In [5]:
# N per DIV
df.groupby(['DIV','Genotype']).size()

DIV  Genotype
4    0           57
     1           55
6    0           54
     1           51
8    0           54
     1           51
10   0           53
     1           46
dtype: int64

In [6]:
grouped_means = data.groupby(['Genotype','DIV','Replicate']).mean();
grouped_means.to_csv('grouped_means.csv');
grouped_means

                         ROI_orig  ROI_eroded  Circularity     Nup153  \
Genotype DIV Replicate
0        4   1          53.714340   42.429690     0.949147   6.184500
             2          46.554136   36.126777     0.944831   7.153186
             3          48.133800   37.417380     0.930807   7.114960
         6   1          56.834300   45.307750     0.958496   6.564789
             2          44.327329   34.251141     0.966120   8.643605
             3          38.556284   28.955274     0.920741   8.732703
         8   1          58.401514   46.697079     0.960960   7.945843
             2          48.685459   38.070982     0.956809   9.083626
             3          50.383850   39.444650     0.942572   9.125277
         10  1          51.305453   40.230000     0.936418   9.270210
             2          47.815674   37.282879     0.958375   9.673752
             3          53.490282   42.131859     0.922486  10.233789
1        4   1          50.344729   39.499835     0.962924   6.033782
             2          50.182450   39.304250     0.949473   6.352939
             3          50.307660   39.345660     0.935888   6.393630
         6   1          56.580382   45.148050     0.970979   6.435991
             2          51.817638   40.792638     0.948009   7.112608
             3          43.296750   33.211519     0.943011   8.242544
         8   1          42.660800   32.537800     0.920915   8.611223
             2          49.754373   38.835982     0.929435   7.675118
             3          41.740405   31.793564     0.929127   9.713733
         10  1          47.751075   37.224270     0.952393   8.245648
             2          42.830400   32.730800     0.933850   9.263751
             3          48.749824   38.017535     0.932454  10.829831

                          JFX554     JF646  JF646_unique
Genotype DIV Replicate
0        4   1          5.329470       NaN           NaN
             2          6.111791       NaN           NaN
             3          6.020307       NaN           NaN
         6   1          5.174950  4.606256      1.516728
             2          6.448536  4.729539      2.000385
             3          6.479415  4.905066      1.772987
         8   1          4.913050  5.709636      2.795300
             2          5.725380  6.422455      2.951360
             3          5.595885  6.633555      3.107319
         10  1          5.038400  7.242847      4.036800
             2          5.683205  7.987871      4.134249
             3          5.654729  7.776112      4.430362
1        4   1          4.953706       NaN           NaN
             2          4.930889       NaN           NaN
             3          5.295740       NaN           NaN
         6   1          5.042032  4.403491      1.315734
             2          5.081308  4.485331      1.364881
             3          5.922600  4.533387      1.505213
         8   1          5.649808  5.991796      2.467955
             2          4.994864  5.075291      2.108818
             3          5.702277  6.570777      3.013765
         10  1          4.887037  6.074669      2.718249
             2          6.066770  6.690812      3.736097
             3          4.934194  7.005140      3.820454

In [7]:
grouped_stdev = data.groupby(['Genotype','DIV','Replicate']).std();
#grouped_stdev.to_csv('grouped_stdev.csv');
grouped_stdev

                         ROI_orig  ROI_eroded  Circularity    Nup153  \
Genotype DIV Replicate
0        4   1           7.049331    6.261334     0.034552  0.799017
             2           9.452638    8.389895     0.038151  0.672372
             3           8.304321    7.314989     0.046200  1.145102
         6   1          11.340255   10.220692     0.036765  0.664130
             2           7.413102    6.554937     0.035418  1.056420
             3           6.249989    5.591339     0.047646  1.094921
         8   1           8.800907    7.805115     0.021169  0.938900
             2           9.939784    8.903956     0.038914  1.221186
             3           7.193768    6.418871     0.036789  1.124988
         10  1           8.956341    7.905015     0.036170  1.041317
             2           7.418878    6.473182     0.032880  1.166277
             3          12.142778   10.844312     0.043870  1.163298
1        4   1           5.656724    5.032901     0.019252  0.860960
             2           7.309835    6.448083     0.025924  0.642212
             3           7.295930    6.485825     0.033487  0.773647
         6   1           9.005139    8.122054     0.024473  0.576007
             2          10.518657    9.359087     0.039351  1.002239
             3           8.467073    7.424671     0.025355  0.774396
         8   1           9.262575    8.110325     0.041210  1.066766
             2          10.043417    8.968500     0.037416  0.425530
             3           7.906625    6.968142     0.030347  1.012677
         10  1          10.942564    9.652767     0.031148  0.929007
             2           2.531500    2.300353     0.020641  0.762845
             3          11.878079   10.537428     0.028699  1.570004

                          JFX554     JF646  JF646_unique
Genotype DIV Replicate
0        4   1          0.661222       NaN           NaN
             2          0.750288       NaN           NaN
             3          0.972020       NaN           NaN
         6   1          0.571054  0.528229      0.344735
             2          0.792932  0.717583      0.486186
             3          0.775132  0.876964      0.603149
         8   1          0.542248  0.726794      0.696186
             2          0.755438  0.923020      0.686263
             3          0.845541  1.056767      0.609060
         10  1          0.775678  0.952063      0.590344
             2          0.749646  0.627893      0.533773
             3          0.637886  0.978639      0.895145
1        4   1          0.607714       NaN           NaN
             2          0.406326       NaN           NaN
             3          0.537339       NaN           NaN
         6   1          0.354082  0.644977      0.420759
             2          0.648317  0.542877      0.382124
             3          0.573018  0.865743      0.432297
         8   1          0.742407  0.704236      0.664925
             2          0.583259  0.366835      0.338306
             3          0.708265  0.743970      0.528330
         10  1          0.627954  0.747636      0.628692
             2          0.566815  1.227481      1.248195
             3          0.599762  1.071035      0.828748

In [8]:
# Make a new column with combined JFX554 + JF646_unique values 

totalHaloSignal = data['JFX554']+data['JF646_unique'].fillna(0);
data['totalJFs'] = totalHaloSignal;

In [9]:
grouped_means = data.groupby(['Genotype','DIV','Replicate']).mean();
grouped_means.to_csv('grouped_means_withtotalHalo.csv');
grouped_stdev = data.groupby(['Genotype','DIV','Replicate']).std();
grouped_stdev.to_csv('grouped_stdev_withtotalHalo.csv');